services:
  postgres-booking:
    image: postgres:latest
    container_name: postgres-booking
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking_service
    ports:
      - "5440:5432"
    volumes:
      - postgres_booking_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking -d booking"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_booking_data:
