// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CheckIn       string                 `protobuf:"bytes,3,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`    // YYYY-MM-DD
	CheckOut      string                 `protobuf:"bytes,4,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"` // YYYY-MM-DD, exclusive
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRoomRequest) Reset() {
	*x = ReserveRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRoomRequest) ProtoMessage() {}

func (x *ReserveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRoomRequest.ProtoReflect.Descriptor instead.
func (*ReserveRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveRoomRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *ReserveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReserveRoomRequest) GetCheckIn() string {
	if x != nil {
		return x.CheckIn
	}
	return ""
}

func (x *ReserveRoomRequest) GetCheckOut() string {
	if x != nil {
		return x.CheckOut
	}
	return ""
}

func (x *ReserveRoomRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ReserveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RoomNumber    string                 `protobuf:"bytes,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	RoomType      string                 `protobuf:"bytes,3,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // minor units
	NightlyRates  []*NightlyRate         `protobuf:"bytes,6,rep,name=nightly_rates,json=nightlyRates,proto3" json:"nightly_rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRoomResponse) Reset() {
	*x = ReserveRoomResponse{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRoomResponse) ProtoMessage() {}

func (x *ReserveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRoomResponse.ProtoReflect.Descriptor instead.
func (*ReserveRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveRoomResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveRoomResponse) GetRoomNumber() string {
	if x != nil {
		return x.RoomNumber
	}
	return ""
}

func (x *ReserveRoomResponse) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *ReserveRoomResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReserveRoomResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *ReserveRoomResponse) GetNightlyRates() []*NightlyRate {
	if x != nil {
		return x.NightlyRates
	}
	return nil
}

type NightlyRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NightlyRate) Reset() {
	*x = NightlyRate{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NightlyRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NightlyRate) ProtoMessage() {}

func (x *NightlyRate) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NightlyRate.ProtoReflect.Descriptor instead.
func (*NightlyRate) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *NightlyRate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NightlyRate) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x12ReserveRoomRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\bcheck_in\x18\x03 \x01(\tR\acheckIn\x12\x1b\n" +
	"\tcheck_out\x18\x04 \x01(\tR\bcheckOut\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xf4\x01\n" +
	"\x13ReserveRoomResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1f\n" +
	"\vroom_number\x18\x02 \x01(\tR\n" +
	"roomNumber\x12\x1b\n" +
	"\troom_type\x18\x03 \x01(\tR\broomType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x03R\vtotalAmount\x129\n" +
	"\rnightly_rates\x18\x06 \x03(\v2\x14.room.v1.NightlyRateR\fnightlyRates\"7\n" +
	"\vNightlyRate\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price2W\n" +
	"\vRoomService\x12H\n" +
	"\vReserveRoom\x12\x1b.room.v1.ReserveRoomRequest\x1a\x1c.room.v1.ReserveRoomResponseB\"Z booking/contracts/room/v1;roomv1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_room_v1_room_proto_goTypes = []any{
	(*ReserveRoomRequest)(nil),    // 0: room.v1.ReserveRoomRequest
	(*ReserveRoomResponse)(nil),   // 1: room.v1.ReserveRoomResponse
	(*NightlyRate)(nil),           // 2: room.v1.NightlyRate
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_room_v1_room_proto_depIdxs = []int32{
	3, // 0: room.v1.ReserveRoomRequest.expires_at:type_name -> google.protobuf.Timestamp
	2, // 1: room.v1.ReserveRoomResponse.nightly_rates:type_name -> room.v1.NightlyRate
	0, // 2: room.v1.RoomService.ReserveRoom:input_type -> room.v1.ReserveRoomRequest
	1, // 3: room.v1.RoomService.ReserveRoom:output_type -> room.v1.ReserveRoomResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
